batch_size: 192
clip_range: 0.2
ent_coef: 0.0
gae_lambda: 0.95
gamma: 0.99
learning_rate: 0.0003
max_grad_norm: 1.0
n_epochs: 12
n_steps: 64
n_timesteps: 16384000.0
normalize_input: false
normalize_value: false
policy: MlpPolicy
policy_kwargs:
  activation_fn: !!python/name:torch.nn.modules.activation.ELU ''
  net_arch:
  - 32
  - 32
  - pi: [256, 128, 64]
    vf: [256, 128, 64]
seed: 42
target_kl: 0.01
vf_coef: 0.0001
